In [1]:
## code snippet to better understand cosine similarity
## bridging the gap between cosine similarity and ML
## tutorial url: https://stackoverflow.com/questions/30089675/clustering-cosine-similarity-matrix

In [7]:
import numpy as np
from sklearn.cluster import SpectralClustering
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

In [3]:
## The algorithm takes the top k eigenvectors of the input matrix
## corresponding to the largest eigenvalues, then runs the k-mean algorithm on the new matrix.
## Here is a simple code that does this for your matrix:

mat = np.matrix([[1.,.1,.6,.4],[.1,1.,.1,.2],[.6,.1,1.,.7],[.4,.2,.7,1.]])
SpectralClustering(2).fit_predict(mat)

C:\Users\liamk\Anaconda3\lib\site-packages\sklearn\cluster\spectral.py:462: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn("The spectral clustering API has changed. ``fit``"


array([0, 1, 0, 0])

In [6]:
eigen_values, eigen_vectors = np.linalg.eigh(mat)
KMeans(n_clusters=2, init='k-means++').fit_predict(eigen_vectors[:, 2:4])

array([0, 1, 0, 0])

In [9]:
## For the cases you want the algorithm to figure out the number of clusters by itself, 
## you can use Density Based Clustering Algorithms like DBSCAN:

DBSCAN(min_samples=1).fit_predict(mat)

array([0, 1, 2, 2], dtype=int64)