In [1]:
## basic tutorial on the formula for cosine similarity
## tutorial url:
## https://www.geeksforgeeks.org/how-to-calculate-cosine-similarity-in-python/

In [2]:
import numpy as np
from numpy.linalg import norm

In [11]:
## Formula:
## Similarity = (A.B) / (||A||.||B||) 
## where A and B are vectors.
## A.B is dot product of A and B: It is computed as sum of element-wise product of A and B.
## ||A|| is L2 norm of A: It is computed as square root of the sum of squares of elements
## of the vector A.

## Explaination:
## The first element of the cosine similarity array is a similarity between the first rows of A and B.
## Similarly second element is the cosine similarity between the second rows of A and B.
## Similarly for the third element.

## We calculate the Cosine Similarity between the two non-zero vectors.
## A vector is a single dimesingle-dimensional signal NumPy array.
## Cosine similarity is a measure of similarity, often used to measure document similarity 
## in text analysis.

In [12]:
# define two arrays
A = np.array([[1,2,2],
               [3,2,2],
               [-2,1,-3]])
B = np.array([[4,2,4],
               [2,-2,5],
               [3,4,-4]])

print("A:\n", A)
print("B:\n", B)

A:
 [[ 1  2  2]
 [ 3  2  2]
 [-2  1 -3]]
B:
 [[ 4  2  4]
 [ 2 -2  5]
 [ 3  4 -4]]


In [13]:
# compute cosine similarity
cosine = np.sum(A*B, axis=1)/(norm(A, axis=1)*norm(B, axis=1))
 
print("Cosine Similarity:\n", cosine)

Cosine Similarity:
 [0.88888889 0.5066404  0.41739194]


In [9]:
## dot product portion
## 4 + 4 + 8 = 16
## 6 - 4 + 10 = 12
## -6 + 4 + 12 = 10
np.sum(A*B, axis=1)

array([16, 12, 10])

In [27]:
## l2 norm portion
## tutorial: understanding np.linalg.norm()
## https://sparrow.dev/numpy-norm/
norm(A, axis=1)

array([3.        , 4.12310563, 3.74165739])